create table product (
	id int primary key,
	name varchar(50),
	description text,
	price decimal(4,2)
);
go
use demo
insert into product (id, name, description, price) values (1, 'Pork Ham Prager', 'quis libero nullam sit amet turpis elementum ligula', 11.12);
insert into product (id, name, description, price) values (2, 'Cheese - Stilton', 'a nibh in quis justo maecenas rhoncus aliquam lacus morbi quis tortor id nulla ultrices', 39.87);
insert into product (id, name, description, price) values (3, 'Cheese - Parmesan Grated', 'pulvinar sed nisl nunc rhoncus dui', 35.9);
insert into product (id, name, description, price) values (4, 'Contreau', 'pellentesque quisque porta volutpat erat quisque erat eros viverra eget congue eget semper', 22.81);
insert into product (id, name, description, price) values (5, 'Butter Sweet', 'praesent lectus vestibulum quam sapien varius ut blandit non', 48.23);
insert into product (id, name, description, price) values (6, 'Cabbage - Savoy', 'morbi vestibulum velit id pretium iaculis diam erat fermentum justo', 47.48);
insert into product (id, name, description, price) values (7, 'Chocolate - Dark', 'ipsum primis in faucibus orci', 20.92);
insert into product (id, name, description, price) values (8, 'Scampi Tail', 'cubilia curae nulla dapibus dolor', 19.33);
insert into product (id, name, description, price) values (9, 'Toothpick Frilled', 'placerat praesent blandit nam nulla integer pede justo lacinia eget', 44.12);
insert into product (id, name, description, price) values (10, 'Chick Peas - Canned', 'faucibus orci luctus et ultrices posuere cubilia curae nulla', 17.39);
insert into product (id, name, description, price) values (11, 'Yukon Jack', 'elit proin interdum mauris non ligula pellentesque ultrices phasellus id sapien in', 40.03);
insert into product (id, name, description, price) values (12, 'Cheese - Comte', 'malesuada in imperdiet et commodo vulputate justo in blandit ultrices enim', 10.82);
insert into product (id, name, description, price) values (13, 'Potatoes - Instant, Mashed', 'at turpis donec posuere metus vitae ipsum aliquam non mauris morbi non lectus', 39.61);
insert into product (id, name, description, price) values (14, 'Cheese - Manchego, Spanish', 'congue eget semper rutrum nulla nunc purus phasellus in felis donec semper', 26.79);
insert into product (id, name, description, price) values (15, 'Chives - Fresh', 'arcu adipiscing molestie hendrerit at vulputate vitae nisl', 37.82);
insert into product (id, name, description, price) values (16, 'Wine - Marlbourough Sauv Blanc', 'justo sollicitudin ut suscipit a feugiat et eros vestibulum ac est lacinia nisi venenatis', 30.18);
insert into product (id, name, description, price) values (17, 'Appetizer - Assorted Box', 'vel est donec odio justo', 27.42);
insert into product (id, name, description, price) values (18, 'Glaze - Apricot', 'ac est lacinia nisi venenatis tristique fusce congue diam id', 27.0);
insert into product (id, name, description, price) values (19, 'Wine - Valpolicella Masi', 'est congue elementum in hac habitasse platea dictumst morbi vestibulum velit id pretium iaculis', 42.14);
insert into product (id, name, description, price) values (20, 'Mushrooms - Black, Dried', 'ultrices enim lorem ipsum dolor', 36.28);
insert into product (id, name, description, price) values (21, 'Sandwich Wrap', 'morbi non lectus aliquam sit amet diam in magna bibendum imperdiet nullam orci', 15.55);
insert into product (id, name, description, price) values (22, 'Amaretto', 'vitae nisl aenean lectus pellentesque', 18.08);
insert into product (id, name, description, price) values (23, 'Nut - Pumpkin Seeds', 'aliquam quis turpis eget elit sodales scelerisque mauris sit amet', 12.52);
insert into product (id, name, description, price) values (24, 'Pecan Raisin - Tarts', 'nullam orci pede venenatis non sodales sed tincidunt eu felis fusce posuere felis sed', 31.7);
insert into product (id, name, description, price) values (25, 'Quail - Jumbo Boneless', 'magna bibendum imperdiet nullam orci pede venenatis non sodales sed', 39.19);
insert into product (id, name, description, price) values (26, 'Cake Slab', 'donec posuere metus vitae ipsum aliquam non mauris morbi non lectus aliquam', 49.51);
insert into product (id, name, description, price) values (27, 'Herb Du Provence - Primerba', 'ut tellus nulla ut erat id', 45.85);
insert into product (id, name, description, price) values (28, 'Lamb - Racks, Frenched', 'lacus curabitur at ipsum ac tellus semper interdum mauris ullamcorper', 30.29);
insert into product (id, name, description, price) values (29, 'Sauce - Roasted Red Pepper', 'sit amet sem fusce consequat nulla nisl nunc nisl duis bibendum felis sed interdum', 27.03);
insert into product (id, name, description, price) values (30, 'Gooseberry', 'etiam justo etiam pretium iaculis justo in hac habitasse platea dictumst etiam faucibus', 16.64);
insert into product (id, name, description, price) values (31, 'Soup - Campbells Chicken', 'a odio in hac habitasse platea dictumst maecenas ut massa quis augue luctus tincidunt', 41.46);
insert into product (id, name, description, price) values (32, 'Wine - Rhine Riesling Wolf Blass', 'aenean sit amet justo morbi ut odio', 49.3);
insert into product (id, name, description, price) values (33, 'Sole - Fillet', 'mi pede malesuada in imperdiet et commodo vulputate justo in blandit ultrices', 42.68);
insert into product (id, name, description, price) values (34, 'Bar - Sweet And Salty Chocolate', 'consequat dui nec nisi volutpat eleifend donec ut dolor', 16.79);
insert into product (id, name, description, price) values (35, 'The Pop Shoppe - Cream Soda', 'in faucibus orci luctus et ultrices posuere cubilia curae donec pharetra magna', 17.05);
insert into product (id, name, description, price) values (36, 'Nut - Pistachio, Shelled', 'amet cursus id turpis integer aliquet massa id lobortis convallis tortor risus dapibus', 13.12);
insert into product (id, name, description, price) values (37, 'Dish Towel', 'consectetuer adipiscing elit proin interdum mauris non ligula pellentesque ultrices phasellus id sapien', 17.56);
insert into product (id, name, description, price) values (38, 'Veal - Kidney', 'fusce lacus purus aliquet at feugiat non pretium quis lectus suspendisse potenti', 21.72);
insert into product (id, name, description, price) values (39, 'Soup - French Onion', 'turpis a pede posuere nonummy integer', 16.76);
insert into product (id, name, description, price) values (40, 'Flour - Chickpea', 'habitasse platea dictumst aliquam augue quam sollicitudin vitae consectetuer eget rutrum at lorem integer tincidunt', 10.1);
insert into product (id, name, description, price) values (41, 'Chocolate - Sugar Free Semi Choc', 'pellentesque at nulla suspendisse potenti cras in purus eu magna vulputate luctus', 35.97);
insert into product (id, name, description, price) values (42, 'Beef - Kindney, Whole', 'habitasse platea dictumst morbi vestibulum velit id pretium iaculis diam erat fermentum justo nec', 29.53);
insert into product (id, name, description, price) values (43, 'Trout - Smoked', 'hac habitasse platea dictumst maecenas ut massa quis augue', 21.19);
insert into product (id, name, description, price) values (44, 'Oil - Macadamia', 'consequat ut nulla sed accumsan felis ut at dolor quis odio', 13.04);
insert into product (id, name, description, price) values (45, 'Oil - Hazelnut', 'sit amet erat nulla tempus vivamus in felis eu sapien', 47.64);
insert into product (id, name, description, price) values (46, 'Onions - Pearl', 'faucibus accumsan odio curabitur convallis duis consequat dui nec nisi volutpat eleifend donec ut', 15.18);
insert into product (id, name, description, price) values (47, 'Wine - Magnotta - Pinot Gris Sr', 'mattis pulvinar nulla pede ullamcorper augue', 40.49);
insert into product (id, name, description, price) values (48, 'Bread - Raisin', 'integer non velit donec diam neque vestibulum eget vulputate ut ultrices vel augue vestibulum ante', 24.76);
insert into product (id, name, description, price) values (49, 'Egg Patty Fried', 'ultrices posuere cubilia curae duis faucibus accumsan odio curabitur convallis duis consequat', 17.13);
insert into product (id, name, description, price) values (50, 'Lamb - Pieces, Diced', 'leo odio porttitor id consequat in consequat ut nulla sed accumsan felis ut at', 15.42);
insert into product (id, name, description, price) values (51, 'Tea - Camomele', 'aenean auctor gravida sem praesent id massa', 29.12);
insert into product (id, name, description, price) values (52, 'Pasta - Fett Alfredo, Single Serve', 'interdum mauris ullamcorper purus sit amet nulla quisque arcu libero rutrum ac', 18.74);
insert into product (id, name, description, price) values (53, 'Puree - Passion Fruit', 'morbi vestibulum velit id pretium', 21.31);
insert into product (id, name, description, price) values (54, 'Langers - Cranberry Cocktail', 'eget orci vehicula condimentum curabitur in libero ut massa volutpat convallis morbi', 38.39);
insert into product (id, name, description, price) values (55, 'Pasta - Rotini, Colour, Dry', 'nec dui luctus rutrum nulla tellus in sagittis dui vel nisl', 44.76);
insert into product (id, name, description, price) values (56, 'Ecolab - Orange Frc, Cleaner', 'lectus suspendisse potenti in eleifend quam a odio in hac habitasse', 37.62);
insert into product (id, name, description, price) values (57, 'Bread Crumbs - Panko', 'scelerisque mauris sit amet eros suspendisse accumsan tortor quis turpis sed ante vivamus tortor', 24.7);
insert into product (id, name, description, price) values (58, 'Muffin - Mix - Strawberry Rhubarb', 'ultrices vel augue vestibulum ante ipsum primis in faucibus orci luctus et', 28.76);
insert into product (id, name, description, price) values (59, 'Lobak', 'odio donec vitae nisi nam ultrices libero non', 23.3);
insert into product (id, name, description, price) values (60, 'Beef - Rib Roast, Capless', 'pretium iaculis diam erat fermentum justo nec condimentum neque', 21.25);
insert into product (id, name, description, price) values (61, 'Garbage Bags - Black', 'mauris vulputate elementum nullam varius nulla facilisi cras non velit nec nisi vulputate nonummy', 31.31);
insert into product (id, name, description, price) values (62, 'Beef - Sushi Flat Iron Steak', 'venenatis turpis enim blandit mi', 11.79);
insert into product (id, name, description, price) values (63, 'Wine - Red, Mosaic Zweigelt', 'integer pede justo lacinia eget tincidunt eget tempus vel', 39.02);
insert into product (id, name, description, price) values (64, 'Turnip - White', 'vitae nisl aenean lectus pellentesque', 49.65);
insert into product (id, name, description, price) values (65, 'Remy Red Berry Infusion', 'semper sapien a libero nam dui proin leo odio porttitor id consequat in', 25.26);
insert into product (id, name, description, price) values (66, 'Wine - White, Chardonnay', 'nunc nisl duis bibendum felis sed interdum venenatis turpis enim', 26.75);
insert into product (id, name, description, price) values (67, 'Tandoori Curry Paste', 'nisl venenatis lacinia aenean sit amet justo morbi ut odio cras mi pede', 45.23);
insert into product (id, name, description, price) values (68, 'Pepsi - 600ml', 'justo nec condimentum neque sapien placerat', 49.47);
insert into product (id, name, description, price) values (69, 'Cream - 10%', 'vestibulum sed magna at nunc commodo placerat praesent blandit nam nulla integer pede justo', 14.55);
insert into product (id, name, description, price) values (70, 'Kellogs All Bran Bars', 'morbi porttitor lorem id ligula suspendisse ornare consequat', 32.2);
insert into product (id, name, description, price) values (71, 'Peach - Halves', 'commodo vulputate justo in blandit ultrices enim lorem ipsum', 25.19);
insert into product (id, name, description, price) values (72, 'Bagelers - Cinn / Brown', 'habitasse platea dictumst morbi vestibulum velit id', 25.11);
insert into product (id, name, description, price) values (73, 'Salt And Pepper Mix - White', 'commodo placerat praesent blandit nam nulla', 15.0);
insert into product (id, name, description, price) values (74, 'Goldschalger', 'quam pharetra magna ac consequat metus sapien ut nunc', 32.34);
insert into product (id, name, description, price) values (75, 'Trueblue - Blueberry 12x473ml', 'hac habitasse platea dictumst maecenas ut massa', 35.96);
insert into product (id, name, description, price) values (76, 'Sobe - Liz Blizz', 'vivamus vestibulum sagittis sapien cum sociis natoque penatibus et magnis dis parturient montes nascetur ridiculus', 38.52);
insert into product (id, name, description, price) values (77, 'The Pop Shoppe - Lime Rickey', 'ipsum primis in faucibus orci', 13.88);
insert into product (id, name, description, price) values (78, 'Yogurt - Blueberry, 175 Gr', 'phasellus id sapien in sapien iaculis congue vivamus metus arcu adipiscing molestie', 45.04);
insert into product (id, name, description, price) values (79, 'Beef - Baby, Liver', 'at lorem integer tincidunt ante vel ipsum praesent', 41.74);
insert into product (id, name, description, price) values (80, 'Taro Leaves', 'curae mauris viverra diam vitae quam suspendisse potenti', 26.27);
insert into product (id, name, description, price) values (81, 'Lamb - Whole, Frozen', 'rutrum neque aenean auctor gravida sem praesent', 25.39);
insert into product (id, name, description, price) values (82, 'Steel Wool S.o.s', 'at nibh in hac habitasse platea dictumst aliquam augue quam sollicitudin vitae consectetuer eget rutrum', 40.24);
insert into product (id, name, description, price) values (83, 'External Supplier', 'adipiscing molestie hendrerit at vulputate vitae nisl aenean lectus pellentesque', 10.01);
insert into product (id, name, description, price) values (84, 'Soup - Campbells, Chix Gumbo', 'tortor duis mattis egestas metus aenean fermentum donec ut mauris eget massa', 36.24);
insert into product (id, name, description, price) values (85, 'Oxtail - Cut', 'amet cursus id turpis integer aliquet massa id lobortis convallis tortor risus dapibus augue vel', 23.3);
insert into product (id, name, description, price) values (86, 'Curry Powder', 'magna at nunc commodo placerat praesent blandit nam nulla', 47.58);
insert into product (id, name, description, price) values (87, 'Egg - Salad Premix', 'erat id mauris vulputate elementum nullam varius nulla facilisi cras non velit nec nisi', 26.61);
insert into product (id, name, description, price) values (88, 'Chocolate - Pistoles, Lactee, Milk', 'curabitur at ipsum ac tellus semper interdum', 42.57);
insert into product (id, name, description, price) values (89, 'Beef - Chuck, Boneless', 'donec dapibus duis at velit', 29.23);
insert into product (id, name, description, price) values (90, 'Wakami Seaweed', 'dolor sit amet consectetuer adipiscing elit', 14.86);
insert into product (id, name, description, price) values (91, 'Smoked Paprika', 'facilisi cras non velit nec nisi vulputate nonummy maecenas tincidunt lacus at velit vivamus vel', 40.03);
insert into product (id, name, description, price) values (92, 'Onions - Dried, Chopped', 'cum sociis natoque penatibus et magnis dis parturient montes', 37.88);
insert into product (id, name, description, price) values (93, 'Bread Foccacia Whole', 'etiam faucibus cursus urna ut tellus', 15.54);
insert into product (id, name, description, price) values (94, 'Oil - Food, Lacquer Spray', 'nunc commodo placerat praesent blandit nam nulla integer', 26.87);
insert into product (id, name, description, price) values (95, 'Artichokes - Jerusalem', 'faucibus accumsan odio curabitur convallis duis consequat dui nec nisi volutpat eleifend donec', 40.98);
insert into product (id, name, description, price) values (96, 'Pork - Bones', 'id ligula suspendisse ornare consequat lectus in est risus', 23.16);
insert into product (id, name, description, price) values (97, 'Chevere Logs', 'odio justo sollicitudin ut suscipit a feugiat et eros vestibulum ac est lacinia', 12.31);
insert into product (id, name, description, price) values (98, 'Chef Hat 25cm', 'donec semper sapien a libero nam dui', 28.97);
insert into product (id, name, description, price) values (99, 'Chocolate Bar - Coffee Crisp', 'rhoncus mauris enim leo rhoncus sed', 23.35);
insert into product (id, name, description, price) values (100, 'Shrimp - 16 - 20 Cooked, Peeled', 'ac est lacinia nisi venenatis tristique fusce congue diam id ornare imperdiet sapien urna', 34.67);
